name: Linux Build

on: [ push, pull_request ]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, windows-2019, windows-2022, macos-10.15, macos-11]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Install conan
      run: |
        python --version
        pip install conan
        conan --version
        echo "Enabling conan revisions and setting parallel_download"
        conan config set general.revisions_enabled=True
        conan config set general.parallel_download=8
        mkdir build/

        if [ "$RUNNER_OS" == "macOS" ]; then
          echo "Setting MACOSX_DEPLOYMENT_TARGET to 10.15"
          echo "MACOSX_DEPLOYMENT_TARGET=10.15" >> $GITHUB_ENV
          echo "Adding SDKROOT to GITHUB_ENV"
          echo "SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" >> $GITHUB_ENV
        fi;

    - name: Configure CMake
      shell: bash
      working-directory: ./build
      run: cmake -DCMAKE_BUILD_TYPE=Release -DLINK_WITH_PYTHON:BOOL=ON ../

    - name: Build MyProgram
      working-directory: ./build
      shell: bash
      run: cmake --build . --target MyProgram -j 2

    - name: Test MyProgram
      working-directory: ./build
      shell: bash
      run: |
         if [ "$RUNNER_OS" == "Windows" ]; then
              ./bin/MyProgram.exe
         else
              ./bin/MyProgram
         fi
